name: Install and Build

on: 
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Show node version
        run: echo node -v

      - name: Install Dependencies
        run: npm run build
